spring.application.name=ExperiMate

#Database (H2)
spring.datasource.url=jdbc:h2:~/experimateDb;AUTO_SERVER=TRUE
spring.datasource.username=
spring.datasource.password=
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.h2.console.enabled=true
spring.datasource.driver-class-name=org.h2.Driver
spring.h2.console.path=/h2-console
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

#JWT
#5 min
jwt.expiration=10000

#RefreshToken
#7 d
refresh-token.expiration=604800000