package hr.tvz.experimate.experimate.model.match;

/**
 * Response DTO for the compatibility explanation between two matched users.
 *
 * @param explanation natural-language sentence generated by {@code AiMatchingService#explainCompatibility}
 */
public record MatchExplanationResponse(String explanation) {}
